
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/todolistDB

spring.datasource.username=postgres

spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# C?u hình "M?c in" (JWT Secret Key)
# (?ây PH?I LÀ m?t chu?i dài và bí m?t, ?? 256 bit - 32 ký t?)
app.jwt-secret=DayLaChuoiBiMatCuaToiDayLaChuoiBiMatCuaToi

# C?u hình "H?n s? d?ng" (JWT Expiration)
# (Tính b?ng mili-giây. 86400000 = 1 ngày)
app.jwt-expiration-milliseconds=86400000