# --- CẤU HÌNH CHO MÔI TRƯỜNG "LOCAL" (DEV) ---

# URL trỏ đến máy thật (localhost)
spring.datasource.url=jdbc:postgresql://localhost:5432/todolistDB 
spring.datasource.username=postgres
spring.datasource.password=123456