# --- CẤU HÌNH CHO MÔI TRƯỜNG "PROD" (DOCKER) ---

# URL trỏ đến TÊN DỊCH VỤ Docker (postgres-db)
spring.datasource.url=jdbc:postgresql://postgres-db:5432/todolistDB 
spring.datasource.username=postgres
spring.datasource.password=123456